name: molhem
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  admob_flutter: ^0.3.1
  screenshot: 0.2.0
  esys_flutter_share: 1.0.2
  share_extend: 1.1.6
  flutter_share_file: 1.1.4+1
  sqflite: any
  path_provider: any
  intl: 0.15.8
    # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
rxdart: ^0.24.1
path_provider: ^1.6.11
http: ^0.12.1

dev_dependencies:
  flutter_launcher_icons: 0.7.5
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.1
  firebase_crashlytics: 0.1.4+1
  cloud_firestore: ^0.13.3
  flutter_staggered_animations: ^0.1.2
  custom_splash : ^0.0.2
  flutter_local_notifications: ^1.3.0
  carousel_slider: ^1.3.0
  shared_preferences: ^0.4.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/background1.jpg
    - assets/images/background2.jpg
    - assets/images/background3.jpg
    - assets/images/background4.jpg
    - assets/images/background5.jpg
    - assets/images/background6.jpg
    - assets/images/background7.jpg
    - assets/images/background8.jpg
    - assets/images/background9.jpg
    - assets/logo/logo1.png
    - assets/splash.png
    - assets/textlogo.png
    - assets/logo/logopng.png
    - assets/logo/ic_stat_lump.png
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo1.png"


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
